######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 10 19:56:31 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . gui resources
INCLUDEPATH += .

SOURCES += gui/tablemodel.py \
           gui/mainwindow.py

# Input
FORMS += gui/aboutdialog.ui gui/mainwindow.ui
RESOURCES += resources/ifmon.qrc

TRANSLATIONS = locale/ifmon_bn.ts
